# Generated by Django 5.2.5 on 2026-01-05 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('vues', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('temps_moyen', models.FloatField(default=0.0, verbose_name='Temps moyen (secondes)')),
            ],
            options={
                'verbose_name': 'Statistique de page',
                'verbose_name_plural': 'Statistiques de pages',
                'db_table': 'stats_page_vue',
                'indexes': [models.Index(fields=['date', 'url'], name='stats_page__date_40ac40_idx'), models.Index(fields=['-vues'], name='stats_page__vues_73168d_idx')],
                'unique_together': {('date', 'url')},
            },
        ),
        migrations.CreateModel(
            name='PaysVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('code_pays', models.CharField(max_length=2, verbose_name='Code pays')),
                ('visites', models.IntegerField(default=0, verbose_name='Visites')),
            ],
            options={
                'verbose_name': 'Visite par pays',
                'verbose_name_plural': 'Visites par pays',
                'db_table': 'stats_pays',
                'unique_together': {('date', 'pays')},
            },
        ),
        migrations.CreateModel(
            name='PeriodeActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.IntegerField(verbose_name='Heure (0-23)')),
                ('visites', models.IntegerField(default=0, verbose_name='Visites')),
            ],
            options={
                'verbose_name': 'Période active',
                'verbose_name_plural': 'Périodes actives',
                'db_table': 'stats_periode_active',
                'unique_together': {('date', 'heure')},
            },
        ),
        migrations.CreateModel(
            name='Referent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('domaine', models.CharField(max_length=200, verbose_name='Domaine')),
                ('url', models.CharField(max_length=500, verbose_name='URL complète')),
                ('visites', models.IntegerField(default=0, verbose_name='Visites')),
            ],
            options={
                'verbose_name': 'Référent',
                'verbose_name_plural': 'Référents',
                'db_table': 'stats_referent',
                'unique_together': {('date', 'domaine')},
            },
        ),
        migrations.CreateModel(
            name='StatsVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de la statistique', unique=True, verbose_name='Date')),
                ('visites', models.IntegerField(default=0, help_text='Nombre total de visites uniques', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de visites')),
                ('pages_vues', models.IntegerField(default=0, help_text='Nombre total de pages consultées', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pages vues')),
                ('visites_authentifiees', models.IntegerField(default=0, help_text='Visites de utilisateurs connectés', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Visites authentifiées')),
                ('duree_moyenne', models.FloatField(default=0.0, help_text='Temps moyen passé sur le site', verbose_name='Durée moyenne (en minutes)')),
                ('taux_rebond', models.FloatField(default=0.0, help_text='Pourcentage de visites avec une seule page vue', verbose_name='Taux de rebond (%)')),
                ('heure', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Heure (0-23)')),
                ('trafic_direct', models.IntegerField(default=0, verbose_name='Trafic direct')),
                ('trafic_reference', models.IntegerField(default=0, verbose_name='Trafic référent')),
                ('trafic_recherche', models.IntegerField(default=0, verbose_name='Trafic recherche')),
                ('trafic_social', models.IntegerField(default=0, verbose_name='Trafic réseaux sociaux')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Statistique de visite',
                'verbose_name_plural': 'Statistiques de visites',
                'db_table': 'stats_visite',
                'ordering': ['-date'],
                'managed': True,
                'indexes': [models.Index(fields=['date'], name='stats_visit_date_d7d822_idx'), models.Index(fields=['created_at'], name='stats_visit_created_2a1dea_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(('visites__gte', 0)), name='visites_positive'), models.CheckConstraint(check=models.Q(('pages_vues__gte', 0)), name='pages_vues_positive'), models.CheckConstraint(check=models.Q(('taux_rebond__gte', 0), ('taux_rebond__lte', 100)), name='taux_rebond_valide')],
            },
        ),
    ]
