# Generated by Django 5.2.5 on 2026-01-08 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_paysvisite_created_at_paysvisite_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodeactive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodeactive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
