# Generated by Django 5.2.5 on 2025-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_evenement', models.DateField(blank=True, help_text="Date historique de l'événement", null=True, verbose_name="Date de l'événement")),
                ('ordre', models.IntegerField(default=0, help_text='Ordre chronologique (plus petit = plus ancien)', verbose_name="Ordre d'affichage")),
                ('image', models.ImageField(blank=True, null=True, upload_to='organisation/historique/', verbose_name='Image')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement Historique',
                'verbose_name_plural': 'Historique',
                'db_table': 'organisation_historique',
                'ordering': ['ordre', 'date_evenement', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembrebureau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-Président'), ('secretaire', 'Secrétaire'), ('secretaire_adjoint', 'Secrétaire Adjoint'), ('tresorier', 'Trésorier'), ('tresorier_adjoint', 'Trésorier Adjoint'), ('conseiller', 'Conseiller'), ('membre', 'Membre')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres_bureau/')),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('mot_du_president', models.TextField(blank=True, help_text="Message du président (visible uniquement si poste='president')", null=True, verbose_name='Mot du Président')),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('mandat_debut', models.DateField(blank=True, null=True)),
                ('mandat_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Membre du Bureau',
                'verbose_name_plural': 'Membres du Bureau',
                'db_table': 'organisation_membrebureau',
                'ordering': ['ordre', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text="Classe CSS ou nom d'icône (ex: 'fa-users', 'shield')", max_length=50, null=True, verbose_name='Icône')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'db_table': 'organisation_mission',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
