# Generated by Django 5.2.5 on 2026-01-05 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotairesNotaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cotisations', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geographie.geographieregion')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geographie.geographieville')),
            ],
            options={
                'db_table': 'notaires_notaire',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotairesCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('impayee', 'Impayée')], default='impayee', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='notaires.notairesnotaire')),
            ],
            options={
                'db_table': 'notaires_cotisation',
                'managed': True,
                'unique_together': {('notaire', 'annee')},
            },
        ),
    ]
