# Generated by Django 5.2.5 on 2026-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notairesnotaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='notaires/photos/', verbose_name='Photo du notaire'),
        ),
    ]
