# Generated by Django 5.2.5 on 2026-01-18 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0002_add_photo_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='notairesnotaire',
            name='assurance_rc_a_jour',
            field=models.BooleanField(default=False, verbose_name='Assurance RC à jour'),
        ),
        migrations.AddField(
            model_name='notairesnotaire',
            name='assurance_rc_date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance de l'assurance RC"),
        ),
        migrations.AlterField(
            model_name='notairescotisation',
            name='statut',
            field=models.CharField(choices=[('payee', 'Payée'), ('impayee', 'Impayée'), ('exceptionnelle', 'Exceptionnelle')], default='impayee', max_length=20),
        ),
        migrations.CreateModel(
            name='NotairesStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='en_cours', max_length=20)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notaire_maitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to='notaires.notairesnotaire')),
            ],
            options={
                'verbose_name': 'Stagiaire Notaire',
                'verbose_name_plural': 'Stagiaires Notaires',
                'db_table': 'notaires_stagiaire',
                'managed': True,
            },
        ),
    ]
