# Generated by Django 5.2.5 on 2026-01-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0003_notairesnotaire_assurance_rc_a_jour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notairesnotaire',
            name='assurance_rc_a_jour',
        ),
    ]
