# Generated by Django 5.2.5 on 2026-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0004_remove_notairesnotaire_assurance_rc_a_jour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notairesnotaire',
            options={},
        ),
        migrations.AlterField(
            model_name='notairesnotaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='notaires/photos/'),
        ),
    ]
