# Generated by Django 4.2.27 on 2026-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0005_alter_notairesnotaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notairesstagiaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='notaires/stagiaires/photos/'),
        ),
    ]
