# Generated by Django 4.2.27 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0006_notairesstagiaire_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notairesnotaire',
            name='ifu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IFU'),
        ),
        migrations.AddField(
            model_name='notairesnotaire',
            name='rscpm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RSCPM'),
        ),
    ]
