# Generated by Django 5.2.5 on 2026-01-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsEmaillog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(max_length=50)),
                ('destinataire', models.CharField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec'), ('ouvert', 'Ouvert'), ('clique', 'Cliqué')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('public_reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'communications_emaillog',
                'managed': True,
                'indexes': [models.Index(fields=['destinataire'], name='communicati_destina_28155d_idx'), models.Index(fields=['sujet'], name='communicati_sujet_0965d6_idx'), models.Index(fields=['statut'], name='communicati_statut_06e2e6_idx'), models.Index(fields=['created_at'], name='communicati_created_35567e_idx'), models.Index(fields=['updated_at'], name='communicati_updated_13ab57_idx')],
            },
        ),
    ]
