# Generated by Django 5.2.5 on 2025-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsEmaillog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(max_length=50)),
                ('destinataire', models.CharField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec'), ('ouvert', 'Ouvert'), ('clique', 'Cliqué')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('public_reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'communications_emaillog',
                'managed': False,
            },
        ),
    ]
