# Generated by Django 5.2.5 on 2026-01-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsSmslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(help_text='Numéro de téléphone du destinataire', max_length=20)),
                ('message', models.TextField(help_text='Contenu du SMS')),
                ('fournisseur', models.CharField(help_text='Fournisseur SMS utilisé (aqilas, orange, moov)', max_length=50)),
                ('sender_id', models.CharField(blank=True, help_text="ID de l'expéditeur", max_length=20, null=True)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec'), ('en_attente', 'En attente'), ('delivre', 'Livré'), ('non_delivre', 'Non délivré')], default='en_attente', max_length=20)),
                ('message_id', models.CharField(blank=True, help_text="ID du message retourné par l'API", max_length=200, null=True)),
                ('erreur', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec", null=True)),
                ('cout_sms', models.DecimalField(blank=True, decimal_places=2, help_text='Coût du SMS en FCFA', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_reference', models.CharField(blank=True, help_text='Référence publique pour tracking', max_length=50, null=True)),
            ],
            options={
                'db_table': 'communications_smslog',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['destinataire'], name='communicati_destina_e70420_idx'), models.Index(fields=['statut'], name='communicati_statut_cb889a_idx'), models.Index(fields=['fournisseur'], name='communicati_fournis_d4e7c9_idx'), models.Index(fields=['created_at'], name='communicati_created_e6a22c_idx'), models.Index(fields=['updated_at'], name='communicati_updated_bde340_idx')],
            },
        ),
    ]
