# Generated by Django 5.2.5 on 2026-01-05 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systememailprofessionnel',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Agent ou responsable utilisant cet email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_professionnels', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
        migrations.AddIndex(
            model_name='systemhealth',
            index=models.Index(fields=['service'], name='system_heal_service_795b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealth',
            index=models.Index(fields=['status'], name='system_heal_status_0a0a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['timestamp'], name='system_log_timesta_2209e3_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['level'], name='system_log_level_48c2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['source'], name='system_log_source_2fd3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['uuid'], name='system_log_uuid_4cef73_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['metric_type'], name='system_metr_metric__622441_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['collected_at'], name='system_metr_collect_b5dd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['name'], name='system_metr_name_fd7721_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['notification_type'], name='system_noti_notific_201b43_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['priority'], name='system_noti_priorit_e4ca36_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_read'], name='system_noti_is_read_311aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_acknowledged'], name='system_noti_is_ackn_e8804c_idx'),
        ),
        migrations.AddIndex(
            model_name='systememailprofessionnel',
            index=models.Index(fields=['email'], name='system_emai_email_2fa45b_idx'),
        ),
        migrations.AddIndex(
            model_name='systememailprofessionnel',
            index=models.Index(fields=['role'], name='system_emai_role_4fd229_idx'),
        ),
        migrations.AddIndex(
            model_name='systememailprofessionnel',
            index=models.Index(fields=['actif'], name='system_emai_actif_522842_idx'),
        ),
    ]
