# Generated by Django 4.2.27 on 2026-02-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementstransaction',
            name='type_paiement',
            field=models.CharField(choices=[('yengapay', 'Yengapay (Orange, Moov, Sank, Telecel)')], max_length=20),
        ),
    ]
