# Generated by Django 5.2.5 on 2025-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('adresse', 'Adresse'), ('telephone', 'Téléphone'), ('email', 'Email'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('valeur', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Pour affichage sur carte (Google Maps)', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Pour affichage sur carte (Google Maps)', max_digits=9, null=True, verbose_name='Longitude')),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information de Contact',
                'verbose_name_plural': 'Informations de Contact',
                'db_table': 'contact_informations',
                'ordering': ['ordre', 'type'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_messages',
                'managed': True,
            },
        ),
    ]
