# Generated by Django 5.2.5 on 2026-01-02 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('permissions', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_userrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(help_text="URL de la page (ex: 'a-propos', 'presentation')", max_length=200, unique=True, verbose_name='Slug')),
                ('contenu', models.TextField(help_text='Contenu HTML de la page', verbose_name='Contenu')),
                ('resume', models.TextField(blank=True, help_text='Résumé court pour les aperçus', max_length=500, null=True, verbose_name='Résumé')),
                ('template', models.CharField(blank=True, default='page_standard.html', help_text='Template à utiliser pour le rendu', max_length=100, null=True, verbose_name='Template')),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO', max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Description SEO', max_length=300, null=True, verbose_name='Meta Description')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Image principale')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('publie', models.BooleanField(default=False, help_text='Si la page est visible publiquement', verbose_name='Publié')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_creees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'core_page',
                'ordering': ['ordre', 'titre'],
                'indexes': [models.Index(fields=['slug'], name='core_page_slug_904ec3_idx'), models.Index(fields=['publie', 'date_publication'], name='core_page_publie_0549a6_idx')],
            },
        ),
    ]
