# Generated by Django 5.2.5 on 2026-01-05 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corepage',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_creees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterUniqueTogether(
            name='authuserrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='corepage',
            index=models.Index(fields=['slug'], name='core_page_slug_904ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='corepage',
            index=models.Index(fields=['publie', 'date_publication'], name='core_page_publie_0549a6_idx'),
        ),
    ]
