# Generated by Django 5.2.5 on 2025-12-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_ajout_core_page'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('permissions', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_userrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_configuration',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='corepage',
            new_name='core_page_slug_904ec3_idx',
            old_name='core_page_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='corepage',
            new_name='core_page_publie_0549a6_idx',
            old_name='core_page_publie_date_idx',
        ),
        migrations.AlterField(
            model_name='corepage',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_creees', to='utilisateurs.utilisateursuser', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='corepage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
