# Generated by Django 5.2.5 on 2026-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualitesActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('contenu', models.TextField()),
                ('resume', models.CharField(blank=True, max_length=500, null=True)),
                ('categorie', models.CharField(choices=[('profession', 'Profession'), ('juridique', 'Juridique'), ('formation', 'Formation'), ('evenement', 'Événement'), ('autre', 'Autre')], max_length=20)),
                ('image_principale', models.CharField(blank=True, max_length=200, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('publie', models.BooleanField(default=False)),
                ('vue', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'db_table': 'actualites_actualite',
                'ordering': ['-date_publication', '-created_at'],
                'managed': False,
            },
        ),
    ]
