# Generated by Django 5.2.5 on 2026-01-05 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actualites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actualitesactualite',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddIndex(
            model_name='actualitesactualite',
            index=models.Index(fields=['slug'], name='actualites__slug_629339_idx'),
        ),
        migrations.AddIndex(
            model_name='actualitesactualite',
            index=models.Index(fields=['publie', 'date_publication'], name='actualites__publie_618c82_idx'),
        ),
        migrations.AddIndex(
            model_name='actualitesactualite',
            index=models.Index(fields=['important', 'date_publication'], name='actualites__importa_c1ab05_idx'),
        ),
        migrations.AddIndex(
            model_name='actualitesactualite',
            index=models.Index(fields=['categorie', 'date_publication'], name='actualites__categor_1ecc19_idx'),
        ),
        migrations.AddIndex(
            model_name='actualitesactualite',
            index=models.Index(fields=['featured', 'date_publication'], name='actualites__feature_76d6f0_idx'),
        ),
    ]
