# Generated by Django 5.2.5 on 2026-01-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualitesactualite',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/photos/', verbose_name='Photo du actualites'),
        ),
    ]
