# Generated by Django 5.2.5 on 2026-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0003_alter_actualitesactualite_image_principale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualitesactualite',
            options={'ordering': ['-date_publication', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='actualitesactualite',
            name='actualites__slug_629339_idx',
        ),
        migrations.RemoveIndex(
            model_name='actualitesactualite',
            name='actualites__publie_618c82_idx',
        ),
        migrations.RemoveIndex(
            model_name='actualitesactualite',
            name='actualites__importa_c1ab05_idx',
        ),
        migrations.RemoveIndex(
            model_name='actualitesactualite',
            name='actualites__categor_1ecc19_idx',
        ),
        migrations.RemoveIndex(
            model_name='actualitesactualite',
            name='actualites__feature_76d6f0_idx',
        ),
        migrations.AlterField(
            model_name='actualitesactualite',
            name='categorie',
            field=models.CharField(choices=[('profession', 'Profession'), ('juridique', 'Juridique'), ('formation', 'Formation'), ('evenement', 'Événement'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='actualitesactualite',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/photos/', verbose_name="Photo de l'actualité"),
        ),
    ]
