# Generated by Django 5.2.5 on 2025-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_heures', models.IntegerField(choices=[(48, '48 heures'), (72, '72 heures')])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentsTextelegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_texte', models.CharField(choices=[('loi', 'Loi'), ('decret', 'Décret'), ('arrete', 'Arrêté'), ('reglement_interieur', 'Règlement intérieur')], max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.CharField(max_length=200)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_textelegal',
                'managed': False,
            },
        ),
    ]
