# Generated by Django 5.2.5 on 2026-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsdocument',
            name='delai_heures',
            field=models.IntegerField(choices=[(5, '5 jours')]),
        ),
    ]
