# Generated by Django 5.2.5 on 2025-12-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
    ]
