# Generated by Django 5.2.5 on 2026-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentsdocument_delai_heures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsdocument',
            name='delai_heures',
            field=models.IntegerField(choices=[(120, '5 jours')]),
        ),
    ]
