# Generated by Django 4.2.27 on 2026-02-12 08:11

from django.db import migrations

def fix_delai_heures(apps, schema_editor):
    DocumentsDocument = apps.get_model('documents', 'DocumentsDocument')
    updated_count = 0
    for doc in DocumentsDocument.objects.all():
        if doc.delai_heures != 120:
            doc.delai_heures = 120
            doc.save()
            updated_count += 1
    print(f"\nFixed {updated_count} documents to 120h (5 days).")

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentsdocument_delai_heures'),
    ]

    operations = [
        migrations.RunPython(fix_delai_heures),
    ]
