# Generated by Django 5.2.5 on 2026-01-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilsConseildujour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conseil', models.TextField()),
                ('date', models.DateField(unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('public_reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'conseils_conseildujour',
                'db_table_comment': "Conseil du jour pour page d'accueil",
                'managed': True,
                'indexes': [models.Index(fields=['date'], name='conseils_co_date_5ef719_idx'), models.Index(fields=['actif'], name='conseils_co_actif_5b06d4_idx'), models.Index(fields=['created_at'], name='conseils_co_created_1d9a28_idx'), models.Index(fields=['updated_at'], name='conseils_co_updated_a2643d_idx')],
            },
        ),
    ]
