# Generated by Django 5.2.5 on 2026-01-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseilsconseildujour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conseilsconseildujour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
