# Generated by Django 5.2.5 on 2026-01-02 02:10

import apps.ventes.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('notaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('taux_reduction', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('actif', models.BooleanField(default=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('client_email', models.EmailField(db_index=True, max_length=254)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_traitement', 'En traitement'), ('terminee', 'Terminée'), ('rejetee', 'Rejetée')], db_index=True, default='en_attente', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('est_payee', models.BooleanField(default=False)),
                ('token_acces', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token_expire', models.DateTimeField(default=apps.ventes.models.token_expire_30j)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='notaires.notairesnotaire')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('client_email', models.EmailField(db_index=True, max_length=254)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20)),
                ('est_payee', models.BooleanField(default=False)),
                ('token_acces', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token_expire', models.DateTimeField(default=apps.ventes.models.token_expire_7j)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('notaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='notaires.notairesnotaire')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='documents.documentsdocument')),
            ],
        ),
        migrations.CreateModel(
            name='VenteSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('client_email', models.EmailField(db_index=True, max_length=254)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20)),
                ('est_payee', models.BooleanField(default=False)),
                ('token_acces', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token_expire', models.DateTimeField(default=apps.ventes.models.token_expire_7j)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('notaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_stickers', to='notaires.notairesnotaire')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_stickers', to='documents.documentsdocument')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], db_index=True, default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.demandevente')),
                ('vente_sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.ventesticker')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('demande__isnull', False), ('vente_sticker__isnull', False), _connector='OR'), name='paiement_demande_ou_vente')],
            },
        ),
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(db_index=True, max_length=254)),
                ('note', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='ventes.demandevente')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='ventes.ventesticker')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sticker', 'client_email'), name='unique_avis_sticker_email'), models.UniqueConstraint(condition=models.Q(('demande__isnull', False)), fields=('demande', 'client_email'), name='unique_avis_demande_email')],
            },
        ),
    ]
