# Generated by Django 5.2.5 on 2025-12-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demande',
            new_name='DemandeVente',
        ),
    ]
