# Generated by Django 5.2.5 on 2025-12-28 23:11

import apps.ventes.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('notaires', '0001_initial'),
        ('ventes', '0002_rename_demande_demandevente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventesticker',
            name='sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_stickers', to='documents.documentsdocument'),
        ),
        migrations.AlterField(
            model_name='ventesticker',
            name='token_expire',
            field=models.DateTimeField(default=apps.ventes.models.token_expire_7j),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('client_email', models.EmailField(db_index=True, max_length=254)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20)),
                ('est_payee', models.BooleanField(default=False)),
                ('token_acces', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token_expire', models.DateTimeField(default=apps.ventes.models.token_expire_7j)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('notaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='notaires.notairesnotaire')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='documents.documentsdocument')),
            ],
        ),
    ]
