# Generated by Django 5.2.5 on 2025-12-28 23:26

import apps.ventes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_alter_ventesticker_sticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventesticker',
            name='token_expire',
            field=models.DateTimeField(default=apps.ventes.models.token_expire_7j),
        ),
    ]
