# Generated by Django 5.2.5 on 2026-01-06 06:54

import apps.ventes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_alter_ventesticker_token_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventesticker',
            name='token_expire',
            field=models.DateTimeField(default=apps.ventes.models.token_expire_7j),
        ),
    ]
