# Generated by Django 5.2.5 on 2026-01-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0019_alter_ventesticker_token_expire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
