# Generated by Django 5.2.5 on 2026-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0020_delete_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventesticker',
            name='code',
            field=models.CharField(default=12345, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
