# Generated by Django 5.2.5 on 2026-01-18 12:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaires', '0003_notairesnotaire_assurance_rc_a_jour_and_more'),
        ('ventes', '0021_ventesticker_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du sticker')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stickers/references/', verbose_name='Image du sticker')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire (FCFA)')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='Stock Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Référence Sticker',
                'verbose_name_plural': 'Références Stickers',
            },
        ),
        migrations.CreateModel(
            name='VenteStickerNotaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('plage_debut', models.CharField(max_length=100, verbose_name='Plage de début (Ex: A1010101)')),
                ('plage_fin', models.CharField(max_length=100, verbose_name='Plage de fin (Ex: A2000002)')),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant Total')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant Payé')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Reste à Payer')),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_notaires', to='notaires.notairesnotaire')),
                ('type_sticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='ventes.referencesticker')),
            ],
            options={
                'verbose_name': 'Vente Sticker Notaire',
                'verbose_name_plural': 'Ventes Stickers Notaires',
                'ordering': ['-date_vente'],
            },
        ),
    ]
