# Generated by Django 4.2.27 on 2026-02-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0022_referencesticker_ventestickernotaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventestickernotaire',
            name='date_recu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventestickernotaire',
            name='mode_reglement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque'), ('versement', 'Versement')], default='espece', max_length=20),
        ),
        migrations.AddField(
            model_name='ventestickernotaire',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
