# Generated by Django 5.2.5 on 2026-01-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandesDemande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('attente_formulaire', 'Attente formulaire'), ('attente_paiement', 'Attente paiement'), ('en_attente_traitement', 'En attente traitement'), ('en_traitement', 'En traitement'), ('document_envoye_email', 'Document envoyé par email'), ('annule', 'Annulé')], default='brouillon', max_length=50)),
                ('donnees_formulaire', models.JSONField(default=dict)),
                ('email_reception', models.EmailField(blank=True, max_length=254, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('document_genere', models.CharField(blank=True, max_length=200, null=True)),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'db_table': 'demandes_demande',
                'managed': False,
            },
        ),
    ]
