# Generated by Django 5.2.5 on 2025-12-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandesDemande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('attente_formulaire', 'Attente formulaire'), ('attente_paiement', 'Attente paiement'), ('en_attente_traitement', 'En attente traitement'), ('en_traitement', 'En traitement'), ('document_envoye_email', 'Document envoyé par email'), ('annule', 'Annulé')], default='brouillon', max_length=50)),
                ('donnees_formulaire', models.JSONField(default=dict)),
                ('email_reception', models.EmailField(blank=True, max_length=254, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('document_genere', models.CharField(blank=True, max_length=200, null=True)),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'db_table': 'demandes_demande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandesPieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('cnib', "CNIB (Carte Nationale d'Identité Burkinabé)"), ('passeport', 'Passeport'), ('document_identite', "Autre document d'identité"), ('document_legal', 'Document légal'), ('autre', 'Autre document')], max_length=30, verbose_name='Type de pièce')),
                ('fichier', models.FileField(help_text='Format accepté: PDF, JPG, PNG (max 10MB)', upload_to='demandes/pieces_jointes/%Y/%m/', verbose_name='Fichier')),
                ('nom_original', models.CharField(blank=True, max_length=255, verbose_name='Nom original du fichier')),
                ('taille_fichier', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (octets)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='demandes.demandesdemande', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'db_table': 'demandes_piecejointe',
                'ordering': ['-created_at'],
            },
        ),
    ]
