# Generated by Django 5.2.5 on 2026-01-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandesdemande',
            name='lien_affiliation',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien d'affiliation"),
        ),
        migrations.AlterField(
            model_name='demandespiecejointe',
            name='type_piece',
            field=models.CharField(choices=[('cnib', "CNIB (Carte Nationale d'Identité Burkinabé)"), ('passeport', 'Passeport'), ('acte_deces', 'Acte de décès'), ('certificat_heredite', "Certificat d'hérédité"), ('document_identite', "Autre document d'identité"), ('document_legal', 'Document légal'), ('autre', 'Autre document')], max_length=30, verbose_name='Type de pièce'),
        ),
    ]
