# Generated by Django 4.2.27 on 2026-02-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandes', '0003_demandesdemande_lien_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandesdemande',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
