# Generated by Django 5.2.5 on 2025-12-28 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAdminactionlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_id', models.IntegerField(blank=True, null=True)),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True)),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_adminactionlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('token_type', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('token_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_tokenusage',
            },
        ),
        migrations.CreateModel(
            name='LoginAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', 'Identifiants invalides'), ('account_inactive', 'Compte inactif'), ('account_locked', 'Compte verrouillé'), ('email_not_verified', 'Email non vérifié'), ('rate_limited', 'Limite dépassée'), ('other', 'Autre')], max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_loginattempt',
                'indexes': [models.Index(fields=['username', 'timestamp'], name='audit_login_usernam_86a7ab_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_login_ip_addr_8dc769_idx'), models.Index(fields=['success', 'timestamp'], name='audit_login_success_c93f07_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Connexion échouée'), ('logout', 'Déconnexion'), ('register', 'Inscription'), ('email_verify_send', 'Envoi vérification email'), ('email_verify_success', 'Vérification email réussie'), ('email_verify_failed', 'Vérification email échouée'), ('sms_verify_send', 'Envoi vérification SMS'), ('sms_verify_success', 'Vérification SMS réussie'), ('sms_verify_failed', 'Vérification SMS échouée'), ('password_change', 'Changement de mot de passe'), ('password_reset_request', 'Demande réinitialisation mot de passe'), ('password_reset_success', 'Réinitialisation mot de passe réussie'), ('profile_update', 'Mise à jour profil'), ('account_lock', 'Compte verrouillé'), ('account_unlock', 'Compte déverrouillé'), ('rate_limit_triggered', 'Limite de tentatives atteinte'), ('token_refresh', 'Renouvellement token'), ('admin_action', 'Action administrateur')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_securitylog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_secur_timesta_06e479_idx'), models.Index(fields=['user', 'timestamp'], name='audit_secur_user_id_16efcf_idx'), models.Index(fields=['action', 'timestamp'], name='audit_secur_action_f5dfaf_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_secur_ip_addr_c350bb_idx')],
            },
        ),
    ]
