# Generated by Django 5.2.5 on 2026-01-05 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditadminactionlog',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginattemptlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattemptlog',
            index=models.Index(fields=['username', 'timestamp'], name='audit_login_usernam_86a7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattemptlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_login_ip_addr_8dc769_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattemptlog',
            index=models.Index(fields=['success', 'timestamp'], name='audit_login_success_c93f07_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['timestamp'], name='audit_secur_timesta_06e479_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_secur_user_id_16efcf_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_secur_action_f5dfaf_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_secur_ip_addr_c350bb_idx'),
        ),
    ]
