# Generated by Django 5.2.5 on 2026-01-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'evenements_evenement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone / WhatsApp')),
                ('email', models.EmailField(max_length=254)),
                ('qualite', models.CharField(choices=[('notaire', 'Notaire'), ('collaborateur', 'Collaborateur de notaire'), ('autre', 'Autre (à préciser)')], max_length=20)),
                ('autre_qualite', models.CharField(blank=True, max_length=100, null=True)),
                ('date_arrivee', models.DateField()),
                ('heure_arrivee', models.TimeField()),
                ('plan_vol', models.FileField(blank=True, null=True, upload_to='evenements/plans_vol/')),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('justificatif_paiement', models.FileField(blank=True, null=True, upload_to='evenements/justificatifs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='evenements.evenement')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'evenements_inscription',
                'managed': True,
            },
        ),
    ]
