# Generated by Django 5.2.5 on 2026-01-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={},
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='autre_qualite',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='date_arrivee',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='justificatif_paiement',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='plan_vol',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='qualite',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='statut_paiement',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenements.evenement'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='evenement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='inscription',
            table=None,
        ),
        migrations.CreateModel(
            name='EvenementChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texte'), ('textarea', 'Zone de texte'), ('number', 'Nombre'), ('date', 'Date'), ('checkbox', 'Case à cocher'), ('select', 'Liste déroulante'), ('file', 'Fichier')], max_length=20)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='evenements.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_texte', models.TextField(blank=True, null=True)),
                ('valeur_nombre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valeur_date', models.DateField(blank=True, null=True)),
                ('valeur_fichier', models.FileField(blank=True, null=True, upload_to='evenements/reponses/')),
                ('valeur_bool', models.BooleanField(null=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenements.evenementchamp')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evenements.inscription')),
            ],
        ),
    ]
