# Generated by Django 5.2.5 on 2026-01-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_alter_evenement_options_alter_inscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('complet', 'Complet'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
