# Generated by Django 5.2.5 on 2026-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_evenement_statut_inscription_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='nombre_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
