# Generated by Django 5.2.5 on 2026-01-26 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0004_evenement_nombre_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionreponse',
            name='valeur_bool',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionreponse',
            name='valeur_fichier',
            field=models.FileField(blank=True, null=True, upload_to='evenements/reponses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
