# Generated by Django 5.2.5 on 2026-01-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0005_alter_inscriptionreponse_valeur_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
